service: transglate

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  stage: prod
  timeout: 15
  region: ap-southeast-2

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          method: any
          path: /{proxy+}
